version: "3.4"
services:
    cadvisor:
        image: gcr.io/google-containers/cadvisor:latest
        container_name: cadvisor
        ports:
            - 8080:8080 # Trên production remove mount port để bên ngoài không accept vào được
        volumes:
            - /:/rootfs:ro
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
    prometheus:
        image: prom/prometheus:latest
        ports:
            - 9090:9090 # Trên production remove mount port để bên ngoài không accept vào được
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        depends_on:
            - cadvisor
    grafana:
        image: grafana/grafana
        ports:
            - 4000:3000 # default user and password is "admin" -> change techvisionus
        volumes:
            - ./data:/var/lib/grafana
        restart: always
        depends_on:
            - prometheus
