scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s # Cứ 5s thì đi lấy data của cAdvisor
      static_configs:
          - targets:
                - cadvisor:8080 #cadvisor là name service, default run on port 8080
