global:
    scrape_interval: 1s
    evaluation_interval: 15s
    external_labels:
        monitor: "Techvisionus Monitoring"

scrape_configs:
    - job_name: cadvisor
      scrape_interval: 5s # Cứ 5s thì đi lấy data của cAdvisor
      scrape_timeout: 2s
      static_configs:
          - targets: ["cadvisor:8080"] #cadvisor là name service, default run on port 8080

    - job_name: node-exporter
      scrape_interval: 5s
      scrape_timeout: 2s
      static_configs:
          - targets: ["node-exporter:9100"]
